packageExtensions:
  'node-fetch@2.6.1':
    dependencies:
      encoding: '*'
  '@mdx-js/loader@1.6.22':
    peerDependencies:
      react: '^16 || ^17'
  '@storybook/core@6.1.15':
    peerDependencies:
      typescript: '*'
      '@emotion/react': '^11'
      '@emotion/babel-plugin': '^11'
  '@storybook/react@6.1.15':
    peerDependencies:
      typescript: '*'
      '@emotion/react': '^11'
      '@emotion/babel-plugin': '^11'
  '@storybook/addon-docs@6.1.15':
    peerDependencies:
      typescript: '*'
      '@emotion/react': '^11'
      '@emotion/babel-plugin': '^11'
  '@storybook/theming@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
  '@storybook/api@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
  '@storybook/addons@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
  '@storybook/addon-knobs@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
  '@storybook/addon-actions@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
  '@storybook/addon-backgrounds@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
  '@storybook/addon-controls@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
  '@storybook/addon-toolbars@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
  '@storybook/addon-essentials@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
      typescript: '*'
      '@emotion/babel-plugin': '^11'
  '@storybook/addon-viewport@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
  '@storybook/ui@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
  '@storybook/source-loader@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
  '@storybook/client-api@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
  '@storybook/components@6.1.15':
    peerDependencies:
      '@emotion/react': '^11'
  'react-dev-utils@10.2.1':
    peerDependencies:
      typescript: '*'
      webpack: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-berry.js
